const types = {
    LOADING_ANI_MODAL_VISIBILITY: 'LOADING_ANI_MODAL_VISIBILITY',
    QRCODE_SCANNER_VISIBILITY: 'QRCODE_SCANNER_VISIBILITY',
    SNACKBAR_VISIBILITY: 'SNACKBAR_VISIBILITY',
    BOTTOM_SHEET_VISIBILITY: 'BOTTOM_SHEET_VISIBILITY',
    BOTTOM_SHEET_UPDATE: 'BOTTOM_SHEET_UPDATE',
    SELECT_DATE_PICKER: 'SELECT_DATE_PICKER'
};

export default types;
